apiVersion: apps/v1
kind: Deployment
metadata:
  name: learning-hub-deployment
spec:
  template:
    spec:
      containers:
      - name: learning-hub-container
        env:
        - name: ENVIRONMENT
          value: "development"
        resources:
          requests:
            memory: "32Mi"
            cpu: "25m"
          limits:
            memory: "64Mi"
            cpu: "50m"
