apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

resources:
- ../../base

patchesStrategicMerge:
- deployment-patch.yaml

replicas:
- name: learning-hub-deployment
  count: 1

images:
- name: learning-hub
  newName: ghcr.io/nmgregorio/fullstack-learning-app
  newTag: ${IMAGE_TAG}
