apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: staging

resources:
- ../../base

replicas:
- name: learning-hub-deployment
  count: 2

images:
- name: learning-hub
  newName: nmgregorio/learning-hub
  newTag: latest

patches:
- path: deployment-patch.yaml
- path: service-patch.yaml
