apiVersion: v1
kind: Service
metadata:
  name: learning-hub-service
  labels:
    app: learning-hub
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30081
    protocol: TCP
  selector:
    app: learning-hub
