apiVersion: apps/v1
kind: Deployment
metadata:
  name: learning-hub-deployment
spec:
  template:
    spec:
      containers:
      - name: learning-hub-container
        env:
        - name: ENVIRONMENT
          value: "staging"
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
